name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
      - name: Integration tests
        run: flutter test integration_test
      - name: Build Android APK
        run: flutter build apk --debug
      - name: Build Web
        run: flutter build web --wasm
      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: app-builds
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/web
